repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.21.3
    hooks:
      - id: commitizen
        name: Lint commit message
        stages:
          - commit-msg

  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
        args: ["--exclude", "venv", "--max-line-length=88"]

      - id: pytest
        name: pytest with coverage
        entry: pytest
        language: system
        types: [python]
        pass_filenames: false
        args:
          - --cov=./
          - --cov-report=term-missing
          - --cov-report=json
          - --cov-fail-under=50
