name: Dockerize And Deploy

on:
  workflow_run:
    workflows: ["Quality, Test"]
    types:
      - completed
    branches:
      -main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/busybe-cloud:latest .

      - name: Tag Docker image for Heroku
        run: docker tag ghcr.io/${{ github.repository_owner }}/busybe-cloud:latest registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web

      - name: Log in to Heroku Container Registry
        run: echo ${{ secrets.HEROKU_API_KEY }} | docker login --username=_ --password-stdin registry.heroku.com

      - name: Push Docker image to Heroku
        run: docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web

      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh

      - name: Set Heroku Stack to Container
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku stack:set container --app ${{ secrets.HEROKU_APP_NAME }}

      - name: Release the app on Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
        run: heroku container:release web --app $HEROKU_APP_NAME

      - name: Notify Slack on deployment success
        if: success()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_MESSAGE: "Deployment successful for ${{ github.repository }} on ${{ github.ref }}: ${{ github.run_id }}"

      - name: Notify Slack on deployment failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_MESSAGE: "Deployment failed for ${{ github.repository }} on ${{ github.ref }}: ${{ github.run_id }}"
